### ISSUE TITLE
Apostrophes and parens in intro text

### ISSUE THREAD

**Issue by JamesC1** [Chadderz121/csud#4]
On MacOS, apostrophes and parens in the makefile intro text (shown by the 'all' target) cause errors in the shell.  eg:

James-MacBook:csud jamescone$ make
/bin/sh: -c: line 0: unexpected EOF while looking for matching `''
/bin/sh: -c: line 1: syntax error: unexpected end of file
make: **\* [all] Error 2
James-MacBook:csud jamescone$

I ahve a patch, but the markup mangles it.  I've failed to work out how to attach it.

**Comment by Chadderz121** [comment]
I've simply removed the apostrophe from the makefile.
Hope this helps.

**Comment by JamesC1** [comment]
Hi Alex,

My patch was a bit more extensive because, after that, I hit problems with
the parens.  I assign copyright to you, to do what you think best.

Regards,
James.

**Comment by JamesC1** [comment]
Hi Alex,

Please have another patch, attached.  I release it into the public domain.

Microsoft natural keyboards contain a USB 1.1 hub.  In order to talk to the
keyboard, or the devices plugged into the keyboard, which are hanging off
that hub, splitting has to occur in the hub that the keyboard is plugged
into, which is the grand-parent of the keyboard.  This patch searches for
the appropriate ancestor.

Things are still not quite right.  After a few minutes, either:
- the whole PI crashes, and starts outputting blank HDMI
  or
- there is an apparently non-recoverable cycle of stall errors, talking to
  the keyboard and the keyboard's hub

Please find attached bad photos of logging related to the next failure,
taken by joining csud's LOGPRINT function to rpi-boot's printf function.
 NB, to reproduce this, you would need to either hack csud to ignore the
fact that USB is already enabled (attached), or to hack rpi-boot not to
enable USB.

Regards,
James.
