### ISSUE TITLE
Out of memory!

### ISSUE THREAD

**Issue by sfan5** [Chadderz121/csud#5]
Debug log:

> CSUD: USB driver version 1.0
> CSUD: HID driver version 1.0
> CSUD: Hub driver version 1.0
> CSUD: Keyboard driver version 1.0
> CSUD: Mouse driver version 1.0
> HCD: Reserving memory.
> Platform: First memory allocation, reserving 16KiB of heap, 256 entries.
> Platform: malloc(0x400) = 0xa9db8. (1023/16384)
> Platform: Out of memory! We should've had more allocations in platform.c.
> Platform: Out of memory! We should've had more allocations in platform.c.
> HCD: Hardware: OT2.80a (BCM2708a)
> HCD: Internal DMA mode.
> HCD: Hardware configuration: 00000000 228ddd50 0ff000e8 1ff00020
> HCD: Host configuration: 00200000
> HCD: Disabling interrupts.
> HCD: Powering USB on.
> HCD: Load completed.
> HCD: Start core.
> Platform: Out of memory! We should've had more allocations in platform.c.
> USBD: Abort, HCD failed to start.
> Platform: free(0xa9db8) (-1/16384)

**Comment by Chadderz121** [comment]
This seems to be an error in the memory manager at startup.
My first guess would be that the bss memory is not intialised to 0, as evidenced by the fact that after allocating 1024 bytes, the heap notes it has allocated 1023 total.
Could you describe your build options and usage of the driver?

**Comment by sfan5** [comment]
Build options:

> TYPE ?= LOWLEVEL
> TARGET ?= RPI
> CONFIG ?= DEBUG
> GNU ?= arm-none-eabi-

Slight modifications to csud:
types.h uses the stdint.h from my kernel
broadcom2835.h doesn't redefine NULL

The kernel just calls UsbInitialise();

**Comment by Chadderz121** [comment]
It doesn't sound like your configuration would do anything wierd.
What about zeroing out the memory? The call to UsbInitialise will not automatically zero out any memory which is uninitialised or has default value 0 (for example allocated in platform.c). Is this zero at the time you call UsbInitialise?

**Comment by sfan5** [comment]
Zeroing out the memory in platform.c makes it go further.
Guess of the problems origin:
arm-linux-gnueabi-gcc expects memset to be avilable -> zeroes out the memory
arm-none-gcc is bare-metal so it may not zero out memory

New Debug log: (No USB devices attached to the RPi in case it matters)

> CSUD: USB driver version 1.0
> CSUD: HID driver version 1.0
> CSUD: Hub driver version 1.0
> CSUD: Keyboard driver version 1.0
> CSUD: Mouse driver version 1.0
> HCD: Reserving memory.
> Platform: First memory allocation, reserving 16KiB of heap, 256 entries.
> Platform: malloc(0x400) = 0xa9ea0. (1023/16384)
> Platform: malloc(0x400) = 0xaa2a0. (2047/16384)
> Platform: malloc(0x8) = 0xaa6a0. (2055/16384)
> HCD: Hardware: OT2.80a (BCM2708a)
> HCD: Internal DMA mode.
> HCD: Hardware configuration: 00000000 228ddd50 0ff000e8 1ff00020
> HCD: Host configuration: 00200000
> HCD: Disabling interrupts.
> HCD: Powering USB on.
> HCD: Load completed.
> HCD: Start core.
> Platform: malloc(0x400) = 0xaa6a8. (3079/16384)
> HCD: Master reset.
> HCD: ULPI FSLS configuration: disabled.
> HCD: DMA configuration: enabled
> HCD: HNP/SRP configuration: HNP, SRP.
> HCD: Core started.
> HCD: Starting host.
> HCD: Host clock: 30-60Mhz.
> HCD: DMA descriptor: disabled.
> HCD: FIFO configuration: Total=0xf000 Rx=0x5000 NPTx=0x5000 PTx=0x5000.
> HCD: Set HNP: enabled.
> HCD: TXFlush(All)
> HCD: RXFlush(ALL)
> HCD: Powering up port.
> HCD: Reset port.
> HCD: Successfully started.
> USBD: Scanning for devices
> Platform: malloc(0x400) = 0xaaaa8. (4135/16384)
> USBD: Allocating new devive, address 0x1.
> USBD: Scanning 1, 480 Mb/s
> HCD: Transfer was not acknowledged.
> HCD: Transfer did not complete.
> HCD: Control message to 0x20300003: 80060001 00001200
> HCD: Request to Unknown Device (Not Ready) failed.
> HCD: Transfer was not acknowledged.
> HCD: Transfer did not complete.
> HCD: Control message to 0x20300003: 80060001 00001200
> HCD: Request to Unknown Device (Not Ready) failed.
> HCD: Transfer was not acknowledged.
> HCD: Transfer did not complete.
> HCD: Control message to 0x20300003: 80060001 00001200
> HCD: Request to Unknown Device (Not Ready) failed.
> HCD: Failed to send to Unknown Device (Not Ready) after 3 attempts.
> HCD: Could not send SETUP to Unknown Device (Not Ready).
> USBD: Message to Unkown Device (Not Ready) timeout reached.
> USBD: Failed to get descriptor 0x1:0x0 for device Unknown Device (Not Ready). Result 0xffffffff8.
> USBD: Failed to read device descriptor for 1.
> USBD: Failed to enumerate devices.
> Platform: free(0xaa6a8) (3111/16384)
> Platform: free(0xa9ea0) (2087/16384)
> Platform: free(0xaa2a0) (1063/16384)
> Platform: free(0xaa6a0) (1055/16384)

**Comment by Chadderz121** [comment]
I'd imagine if you had a problem with zeroing out in one place, you may well have that problem all over.

You can quite easily zero out all the uninitialised memory, as the compiler places it all in an adjacent section named ".bss". GCC in particular defines the symbols "**bss_start**" and "**bss_end**" at the start and end of this section. So something along the lines of:

``` C
extern char[] __bss_start__;
extern char[] __bss_end__;
```

``` C
    memset(__bss_start__, 0, __bss_end__ - __bss_start__);
```

Should zero out all such memory. I'm making a few assumptions about your compiler and setup, so this may not work in practice. You'd need to do this when your main executable is loaded, as the compiler will merge all .bss sections, including those from your own kernel if any.

**Comment by sfan5** [comment]
When I zero out .bss I get this:

> CSUD: USB driver version 1.0
> CSUD: HID driver version 1.0
> CSUD: Hub driver version 1.0
> CSUD: Keyboard driver version 1.0
> CSUD: Mouse driver version 1.0
> HCD: Reserving memory.
> Platform: First memory allocation, reserving 16KiB of heap, 256 entries.
> Platform: Out of memory! We should've had more allocations in platform.c.
> Platform: Out of memory! We should've had more allocations in platform.c.
> Platform: Out of memory! We should've had more allocations in platform.c.
> HCD: Hardware: OT2.80a (BCM2708a)
> HCD: Internal DMA mode.
> HCD: Hardware configuration: 00000000 228ddd50 0ff000e8 1ff00020
> HCD: Host configuration: 00200000
> HCD: Disabling interrupts.
> HCD: Powering USB on.
> HCD: Load completed.
> HCD: Start core.
> HCD: HCD uninitialised. Cannot be started.
> USBD: Abort, HCD failed to start.

Since __bss_start__ and __bss_end__ were not defined I changed the bss part of kernel.ld to this:

<pre>
.bss : {
    __bss_start__ = . ;
    *(.bss)
    __bss_end__ = . ;
}
</pre>

**Comment by mntmn** [comment]
Hey, I had this problem too. I fixed it by zeroing out the bss as you mentioned. It did not work when declaring **bss_start** and end as char[], though, as they wouldn't be correctly set by the linker. This worked for me:

```
extern unsigned char __bss_start__;
extern unsigned char __bss_end__;

void setup() {
    // zero out bss
    dst = &__bss_start__;
    while(dst < &__bss_end__) *dst++ = 0;
}
```

Got this from reply #3 in http://forums.codeblocks.org/index.php?topic=12374.0

Maybe this will help someone.

Cheers!
